name: Build gatsby and push static code to gatsby-test-build

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest
    env:
      HOTJAR_ID: "2764436"
      HOTJAR_SNIPPET_VERSION: "6"
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: my-gatsby-site
      
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli@2.18.0

      - name: Install yarn
        run: npm install -g yarn

      - name: Install Project Dependencies
        run: cd my-gatsby-site && yarn
      
      - name: Build
        run: "HOTJAR_ID=${{env.HOTJAR_ID}} HOTJAR_SNIPPET_VERSION=${{env.HOTJAR_SNIPPET_VERSION}} cd my-gatsby-site && gatsby build"
      
      - name: Verify build
        run: ls -la my-gatsby-site/public

      - name: Checkout Build Repo
        uses: actions/checkout@v2
        with:
          repository: msarauer/gatsby-test-build
          # token: ${{ secrets.PUSH_TO_BUILD }} # `GitHub_PAT` is a secret that contains your PAT
          path: gatsby-test-build
      - run: |
          cp -RT my-gatsby-site/public gatsby-test-build
          mkdir -p gatsby-test-build/.github/workflows && cp my-gatsby-site/buildworkflow_prod.yml gatsby-test-build/.github/workflows/buildworkflow.yml
          cd gatsby-test-build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deployed ${{ steps.date.outputs.date }}"
          git push